name: donor
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^0.4.5
  firebase_auth: ^0.16.1
  firebase_storage: ^3.1.6
  cloud_firestore: ^0.13.7
  image_picker: ^0.6.7+4
  google_fonts: ^1.1.0
  image_cropper: ^1.2.3
  cool_stepper: ^1.0.0+2
  flutter_icons: ^1.1.0
  cupertino_icons: ^0.1.3
  get: ^3.4.2
  provider: ^4.3.1
  flushbar: ^1.10.4
  custom_radio_grouped_button: ^1.0.2
  modal_bottom_sheet: ^0.2.0+1
  combos: ^1.2.0


dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
  - assets/images/